-- JULI3TA per-app tracks table.
-- Holds AI-generated song metadata. Audio bytes live in the user's
-- Music folder via host.fs (referenced by `file_node_id`); the cover
-- art image bytes also live in the user's filesystem. Lyrics + prompt
-- are stored inline in this row because they're small and queryable.

CREATE TABLE IF NOT EXISTS tracks (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  prompt TEXT NOT NULL DEFAULT '',
  lyrics TEXT NOT NULL DEFAULT '',
  -- ISO 8601 UTC. Created_at is set on insert and never updated.
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  -- File-node ids in host.fs. Both nullable: a track can exist as a
  -- "draft" (lyrics only) before generation produces audio + cover.
  audio_file_node_id TEXT,
  cover_file_node_id TEXT,
  -- The model id that produced the audio (e.g. `minimax:music-2.6`).
  -- Useful for filtering "generated by X" later.
  model_id TEXT,
  -- BPM, key, duration_seconds — populated post-generation when known.
  bpm INTEGER,
  key TEXT,
  duration_seconds REAL,
  -- 1 = user-favourited. The library gallery sorts by this when set.
  favourited INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS tracks_created_at ON tracks(created_at DESC);
CREATE INDEX IF NOT EXISTS tracks_favourited ON tracks(favourited DESC, created_at DESC);
